* Blink in Verlisp

  This is one of the classic "blink the LEDs" programs written in
  Verilisp, closely modelled on the many Verilog examples of the same
  functionality available online.

  The program is intended for the Lattice IceStick FPGA development
  board, which has a small number of on-board LEDs. The file ~blink.pcf~
  is a constraints file that binds variables (in the program) to pins
  (one the board) to make sure that they control the LEDs. These could
  be changed very simply to drive off-board LEDs.

** Running on the Lattice IceStick

   The Makefile contains a line of the form:

   #+begin_src makefile
include $(VERILISP_ROOT)/examples/icestick.mk
   #+end_src

   Make sure this line is uncommented, and any other similar lines in
   its neighbourhood are commented. Then run ~make~ followed by ~make
   upload~ (with the device plugged in to a USB port, obviously).

** Running on the Digilent CMOD A7

   Comment the IceStick include line and uncomment the one for the
   Digilent device. For the latter, start a shell using:

   #+begin_src sh
nix develop github:openxc7/toolchain-nix
make
make upload
   #+end_src

   Or you can run the commands directly in the shell:

   #+begin_src sh
nix develop github:openxc7/toolchain-nix --command make
nix develop github:openxc7/toolchain-nix --command make upload
   #+end_src
