;;;; Variable annotation declarations
;;;;
;;;; Copyright (C) 2024--2026 Simon Dobson
;;;;
;;;; This file is part of verilisp, a very Lisp approach to hardware synthesis
;;;;
;;;; verilisp is free software: you can redistribute it and/or modify
;;;; it under the terms of the GNU General Public License as published by
;;;; the Free Software Foundation, either version 3 of the License, or
;;;; (at your option) any later version.
;;;;
;;;; verilisp is distributed in the hope that it will be useful,
;;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;;; GNU General Public License for more details.
;;;;
;;;; You should have received a copy of the GNU General Public License
;;;; along with verilisp. If not, see <http://www.gnu.org/licenses/gpl.html>.

(in-package :verilisp/core)

;;; We support a different set of annotations to those in Common Lisp.

;;; TODO: Add optimisation annotations to the environment so that they
;;; can be used by passes.


(defpassmethod expand-macros (declare &rest clauses)
  (let ((eclauses (mapcar (lambda (clause)
			    (destructuring-bind (annotation &rest args)
				clause
			      `(,annotation ,@ (mapcar #'expand-macros args))))
			  clauses)))

    `(declare ,@eclauses)))


(defpassmethod compute-type (declare &rest args)
  t)


(defpassmethod float-let-blocks (declare &rest args)
  ;; delete declarations when blocks are floated
  '(() ()))


(defpassmethod synthesise (declare &rest args)
  nil)


(defpassmethod read-variables (declare &rest args)
  '())


;;; TODO: Should this be its own pass?

(defpassmethod add-frames (declare &rest args)
  (mapc (lambda (dec)
	  (with-current-form dec
	    (destructuring-bind (tag &rest decargs)
		dec
	      (declare-annotation tag decargs))))
	args)

  ;; return form unaltered
  `(declare ,@args))


;;; This is a little aggressive, as some declarations might make sense
;;; to Lisp as well as to Verilisp. But most won't, so it's safer to
;;; drop them all.

(defpassmethod lispify (declare &rest args)
  nil)


;;; ---------- Declaring annotations ----------

;;; TODO: This should be a pass, to let the annotation structure
;;; be clearly bound to syntax.

(defgeneric declare-annotation (tag args)
  (:documentation "Handle the annotation declaration TAG with ARGS.

Methods on this function should add information about the
annotation to the current frame of the global environment,
so use in later passes.

Unrecognised annotations are ignored with a warning.")
  (:method (tag args)
    (warn 'unrecognised-declaration :tag tag)))


;;; ---------- Standard annotations ----------

(defmethod declare-annotation ((tag (eql 'type)) args)
  (destructuring-bind (ty &rest vars)
      args
    (dolist (n vars)
      (ensure-variable-declared-in-current-frame n)

      ;; set the explicit type
      (set-variable-property n 'type ty)

      ;; ... and add as a constraint
      (add-type-constraint n ty))))


;; width -- short form of type specification

(defmethod declare-annotation ((tag (eql 'width)) args)
  (destructuring-bind (width &rest vars)
      args
    ;; width is a shortcut for an unsigned-byte type
    (declare-annotation 'type (cons `(unsigned-byte ,width) vars))))


;; type -- set a type explicitly rather than letting it be inferred

(defmethod declare-annotation ((tag (eql 'as)) args)
  (destructuring-bind (rep &rest vars)
      args
    (dolist (n vars)
      (ensure-variable-declared-in-current-frame n)
      (set-variable-property n 'as rep))))


;; direction -- set a parameter direction rather than letting it be inferred

(defmethod declare-annotation ((tag (eql 'direction)) args)
  (destructuring-bind (rep &rest vars)
      args
    (dolist (n vars)
      (ensure-variable-declared-in-current-frame n)
      (set-variable-property n 'direction rep))))


;; ignore and ignorable -- prevent warnings

(defmethod declare-annotation ((tag (eql 'ignore)) args)
  (dolist (n args)
    (ensure-variable-declared-in-current-frame n)
    (set-variable-property n 'ignore t)))


(defmethod declare-annotation ((tag (eql 'ignorable)) args)
  (dolist (n args)
    (ensure-variable-declared-in-current-frame n)
    (set-variable-property n 'ignorable t)))


;;; ---------- Standartd special annotations, mainly intended for the compiler ----------

;; compiler-flag -- set a compiler flag within a scope

(defmethod declare-anotation ((tag (eql 'compiler-flag)) args)
  (destructuring-bind (dvar dval)
      args
    (set-compiler-flag dvar dval)))


;; synthetic -- mark variable as generated by the compiler

(defmethod declare-annotation ((tag (eql 'synthetic)) args)
  (dolist (n args)
    (ensure-variable-declared-in-current-frame n)
    (set-variable-property n 'synthetic t)))


;; assigned-at-declaration -- prevent local assignment when floating

(defmethod declare-annotation ((tag (eql 'assigned-at-declaration)) args)
  (dolist (n args)
    (ensure-variable-declared-in-current-frame n)

    ;; this is the same property used internally to mark variables
    ;; whose LET blocks have been floated, which inhibits their
    ;; initial value being re-assigned if their block is floated again
    (set-variable-property n 'floated t)))
